apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: lily
  name: lily
  namespace: media # Make sure this matches your namespace

spec:
  ports:
    - name: http
      port: 8083
  selector:
    app.service: lily
