"""Builds cps/static/css/lily-icons.css, which draws every Glyphicon class the
app uses as the matching Lucide icon (cps/static/icons/lucide, v1.48.0, ISC).

    python3 scripts/build_icons.py

Templates keep their <span class="glyphicon glyphicon-..."> markup, so JS that
swaps icon classes keeps working. A class missing from ICONS falls back to the
Glyphicons font. To add one, drop the SVG from lucide-static into the icons
folder, map it below and rerun.
"""
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "cps/static/icons/lucide"
OUT = ROOT / "cps/static/css/lily-icons.css"

# Glyphicon name -> Lucide name. Names ending in "+fill" are drawn filled.
ICONS = {
    "ban-circle": "ban",
    "book": "book-open",
    "bookmark": "bookmark",
    "collapse-down": "chevron-down",
    "collapse-up": "chevron-up",
    "copy": "copy",
    "dashboard": "gauge",
    "download": "download",
    "download-alt": "download",
    "duplicate": "copy",
    "edit": "square-pen",
    "eye-close": "eye-off",
    "eye-open": "eye",
    "file": "file",
    "filter": "funnel",
    "fire": "flame",
    "flag": "flag",
    "flash": "zap",
    "folder-close": "folder",
    "folder-open": "folder-open",
    "font": "type",
    "fullscreen": "maximize",
    "inbox": "inbox",
    "indent-left": "list-indent-decrease",
    "indent-right": "list-indent-increase",
    "info-sign": "info",
    "link": "link",
    "list": "library",
    "list-alt": "list",
    "lock": "lock",
    "menu-hamburger": "menu",
    "minus": "minus",
    "music": "music",
    "ok": "check",
    "option-horizontal": "ellipsis",
    "ok-circle": "circle-check",
    "pencil": "pencil",
    "picture": "image",
    "plus": "plus",
    "random": "shuffle",
    "refresh": "refresh-cw",
    "remove": "x",
    "remove-circle": "circle-x",
    "search": "search",
    "send": "send",
    "share": "share-2",
    "sort": "arrow-up-down",
    "sort-by-alphabet": "arrow-down-a-z",
    "sort-by-alphabet-alt": "arrow-down-z-a",
    "sort-by-attributes": "arrow-up-narrow-wide",
    "sort-by-attributes-alt": "arrow-down-wide-narrow",
    "star": "star+fill",
    "star-empty": "star",
    "stats": "chart-column",
    "tag": "tag",
    "tags": "tags",
    "tasks": "list-checks",
    "text-size": "type",
    "th": "grid-3x3",
    "th-large": "layout-grid",
    "th-list": "list",
    "trash": "trash-2",
    "upload": "upload",
    "user": "user",
    "warning-sign": "triangle-alert",
}


def svg_data_uri(name):
    filled = name.endswith("+fill")
    svg = (SRC / (name.removesuffix("+fill") + ".svg")).read_text()
    svg = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    # Size comes from CSS: drop the root tag's own size (not the shapes').
    svg = re.sub(r"<svg[^>]*>", lambda m: re.sub(r'\s(class|width|height)="[^"]*"', "", m.group(0)), svg, count=1)
    # Used as a mask, so only the alpha counts: draw in solid black.
    svg = svg.replace('stroke="currentColor"', 'stroke="#000"')
    if filled:
        svg = svg.replace('fill="none"', 'fill="#000"')
    svg = re.sub(r">\s+<", "><", " ".join(svg.split())).strip()
    svg = svg.replace('"', "'").replace(" />", "/>").replace(" >", ">")
    return "data:image/svg+xml," + quote(svg, safe=" =:/',.-")


def main():
    classes = sorted(ICONS)
    selectors = ",\n".join(f".glyphicon-{c}::before" for c in classes)
    lines = [
        "/* Generated by scripts/build_icons.py - edit that, not this file.",
        "   Icons: Lucide (https://lucide.dev), ISC License, see",
        "   cps/static/icons/lucide/LICENSE. */",
        "",
        "/* Lucide draws on a 24px grid with 2px of air, so the mask box is 1.2em",
        "   to match the optical size of the Glyphicon it replaces, with negative",
        "   margins so the span keeps its 1em footprint. */",
        f"{selectors} {{",
        '    content: "";',
        "    display: block;",
        "    width: 1.2em;",
        "    height: 1.2em;",
        "    margin: -0.1em;",
        "    background-color: currentColor;",
        "    -webkit-mask: var(--lily-icon) center / contain no-repeat;",
        "    mask: var(--lily-icon) center / contain no-repeat;",
        "}",
        "",
        "/* High contrast: keep the fill (the forced text colour) instead of",
        "   letting the browser replace the background. */",
        "@media (forced-colors: active) {",
        f"    {selectors.replace(chr(10), chr(10) + '    ')} {{ forced-color-adjust: none; }}",
        "}",
        "",
    ]
    for c in classes:
        lines.append(f'.glyphicon-{c} {{ --lily-icon: url("{svg_data_uri(ICONS[c])}"); }}')
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(classes)} icons")


if __name__ == "__main__":
    main()
